apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example
  namespace: metallb-system
spec:
  # addresses:
  # - 172.18.255.200-172.18.255.250
  {{- with .Values.metallb.IPAddressPool.addresses }}
  addresses:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system